SELECT
PRODUCT_ALIAS.PA_ALIASCODE AS SKU,
PH_STARTDATE AS STARTDATE,
PH_ENDDATE AS ENDDATE,
PR_PRICE as PROMO_PRICE,
PM_STDSELLINGPRICE AS STD_SELLING_PRICE,
PH_NAME
FROM PRODUCT_LEDGER
LEFT OUTER JOIN PRODUCTS ON PRODUCT_LEDGER.PL_PRODUCTCODE = PRODUCTS.PM_PRODUCTCODE AND PRODUCTS.PM_IS_WEB = 1
LEFT OUTER JOIN PROMOTION_DETAIL ON PRODUCTS.PM_PRODUCTCODE = PROMOTION_DETAIL.PR_PRODUCTCODE
LEFT OUTER JOIN PROMOTION_HEADER ON PROMOTION_HEADER.PH_ID = PROMOTION_DETAIL.PR_ID
INNER JOIN PRODUCT_ALIAS ON PRODUCT_ALIAS.PA_PRODUCTCODE = PRODUCTS.PM_PRODUCTCODE
WHERE PRODUCT_LEDGER.PL_PRODUCTCODE <> 'VOUCHER'
AND PRODUCT_LEDGER.PL_STORE_ID IN (50)
AND PROMOTION_HEADER.PH_STATUS = 1
AND PRODUCT_LEDGER.PL_LOCATION_ID=0
AND PRODUCTS.PM_STOCKTYPE = 0
GROUP BY PA_ALIASCODE,
PH_STARTDATE,
PH_ENDDATE,
PR_PRICE,
PM_STDSELLINGPRICE,
PH_NAME